name: "Get data"
on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # otherwise, you will failed to push refs to dest repo
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Install requirenments
      run: |
        install.packages(c("data.table","XML", "dplyr", "ISOweek", "RCurl", "stringi"), dependencies=TRUE)

    - name: Get data
      run: |
        #cd ./code
        Rscript ./get_snapshots.R	
        #cd ../
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Build visualization"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/covid19-forecast-hub-de.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit -m "Daily data update"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:master
        echo "pushed to github"
