name: "Get data"
on:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # otherwise, you will failed to push refs to dest repo
    
    - uses: r-lib/actions/setup-r@v1
    - uses: r-lib/actions/setup-renv@v1
      with:
        cache-version: 1
    
#     - uses: r-lib/actions/setup-r-dependencies@v1
#       with:
#         cache-version: 1

    - name: Get data
      run: |
        Rscript ./get_snapshots.R	
        
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - Build visualization"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/KITmetricslab/covid19-forecast-hub-de.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit -m "Daily data update"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:master
        echo "pushed to github"
